# Generated by Django 3.2.1 on 2021-05-05 21:18

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemdeentrega',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='ordemdeentrega',
            name='data',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='data',
        ),
        migrations.AddField(
            model_name='pedido',
            name='dataPedido',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='valor',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordemdeentrega',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
