# Generated by Django 3.1.7 on 2021-06-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.IntegerField()),
                ('nome', models.CharField(max_length=200)),
                ('senha', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=254)),
                ('cep', models.IntegerField()),
                ('rua', models.CharField(max_length=200)),
                ('bairro', models.CharField(max_length=200)),
            ],
        ),
    ]
